# Generated by Django 4.1.2 on 2022-10-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
